version: '2'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile.php
    volumes:
      - ./:/app
    links:
      - database

  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    volumes_from:
      - php
    links:
      - php

  database:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: json_api
      MYSQL_USER: api_user
      MYSQL_PASSWORD: 4[TUW7z3>QG9(Yh38,Wjsw
