version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes_from:
      - data
    links:
      - php
    environment:
      DEBUG: 'true'

  data:
    volumes:
      - ./:app
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./
    volumes_from:
      - data
    links:
      - database

  database:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 4[TUW7z3>QG9(Yh38,Wjsw
