version: '2'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile.php
    volumes:
      - ./:/app
    links:
      - database

  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    volumes_from:
      - php
    links:
      - php

  database:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_password
